stages:
  - environment
  - build
  - test
  - release

buildDebug:
  image: mysteriumnetwork/mobile-ci:1.0.1
  stage: build
  tags: [docker]
  except:
    refs:
      - tags
    changes:
      - "./fastlane/android_version_code"
  before_script:
    - bundle install
    - echo "$GOOGLE_SERVICES_VALUE" | base64 --decode > "$GOOGLE_SERVICES_PATH"
  script:
    - bundle exec fastlane buildDebug

testDebug:
  image: mysteriumnetwork/mobile-ci:1.0.1
  stage: test
  tags: [docker]
  except:
    refs:
      - tags
    changes:
      - "./fastlane/android_version_code"
  dependencies:
    - buildDebug
  before_script:
    - bundle install
    - echo "$GOOGLE_SERVICES_VALUE" | base64 --decode > "$GOOGLE_SERVICES_PATH"
  script:
    - bundle exec fastlane test

publishInternal:
  image: mysteriumnetwork/mobile-ci:1.0.1
  stage: release
  only: [tags]
  tags: [docker]
  before_script:
    - bundle install
    - echo "$FASTLANE_ANDROID_SIGNING_FILE_VALUE" | base64 --decode > "$FASTLANE_ANDROID_SIGNING_FILE_PATH"
    - echo "$FASTLANE_ANDROID_SECRET_JSON_VALUE" | base64 --decode > "$FASTLANE_ANDROID_SECRET_JSON_PATH"
    - echo "$GOOGLE_SERVICES_VALUE" | base64 --decode > "$GOOGLE_SERVICES_PATH"
  script:
    - bundle exec fastlane internal
    - bundle exec fastlane build
    - apt update; apt install -y jq
    - RELEASE_ID=$(curl -s -H "Authorization:token $GITHUB_API_TOKEN" https://api.github.com/repos/mysteriumnetwork/mysterium-vpn-mobile/releases/tags/$CI_COMMIT_TAG | jq -r .id)
    - curl --data-binary @android/app/build/outputs/apk/release/app-release.apk -H "Authorization:token $GITHUB_API_TOKEN" -H "Content-Type:application/octet-stream" https://uploads.github.com/repos/mysteriumnetwork/mysterium-vpn-mobile/releases/$RELEASE_ID/assets?name=myst.apk
